# ===============================
# Application
# ===============================
spring.application.name=backend
server.port=8080

# ===============================
# PostgreSQL - DEV
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/legalaid_db
spring.datasource.username=postgres
spring.datasource.password=happy
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===============================
# Flyway (disabled for now)
# ===============================
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# ===============================
# JWT
# ===============================
jwt.secret=ThisIsASecretKeyForLegalAidPlatform123456
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000
